source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AURCherryBlossomView_Example', :exclusive => true do
  pod 'AURCherryBlossomView', :path => '../'
end

target 'AURCherryBlossomView_Tests', :exclusive => true do
  pod 'AURCherryBlossomView', :path => '../'

  
end
